language: node_js
node_js:
  - 'stable'
install: npm install
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=testing
    - EMAIL_KEY='kjnkj'
    - EMAIL_DOMAIN='igöl'
services:
  - postgresql
before_script:
  - psql -c 'create database qualityhub_test;' -U postgres
  - psql -c "CREATE USER quality WITH PASSWORD 'root';" -U postgres
script: npm test
