language: node_js
node_js:
  - 'stable'
install: npm install
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=testing
services:
  - postgresql
before_script:
  - psql -c 'create database qualityhub_test;' -U postgres
  - psql -c "CREATE USER postgres-1 WITH PASSWORD 'root';" -U postgres

script: npm test
