# The name of the workflow
name: Dev-Coach

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on:
  pull_request:
  push:
    branches:
      - master

# The jobs that will be run, usually in parallel
jobs:
  # A job to generate and publish code coverage
  coverage:
		# A more descriptive name of the job
    name: Test and publish test coverage

    # The OS on which the job will run
    runs-on: ubuntu-latest

    # The steps for the job, executed in sequence
    steps:
			
      # A GitHub action for checking out the current branch
      - uses: actions/checkout@master

      # A GitHub action to setup Node.js
      - uses: actions/setup-node@master
        with:
          node-version: "12"

      # Run the NPM install command before proceeding
      - run: npm install

      # A GitHub action for running tests and publishing coverage
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          # An environment variable, the value is a GitHub repo secret
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          DATABASE_DEV: ${{ secrets.DATABASE_DEV }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TEST: ${{ secrets.DATABASE_TEST }}
          SECRET: ${{ secrets.SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEREPORTERID }}
        with:
          # Run our `coverage` script in our `package.json`
          coverageCommand: npm run coverage
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
          coverageLocations: "./coverage/clover.xml:clover"
          # Great for troubleshooting
          debug: true